remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ELLIS Machine Learning for Molecules Discovery workshop [ML4Molecules]
description: ELLIS workshop, VIRTUAL, Mid December, 2023, unofficial NeurIPS2023 side-event
