remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Critical assessment of molecular machine learning workshop [ML4Molecules]
description: ELLIS workshop, VIRTUAL, November 28, 2022, unofficial NeurIPS2022 side-event
