remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Advancing Molecular Machine Learning - Overcoming Limitations [ML4Molecules]
description: ELLIS workshop, VIRTUAL, December 8, 2023, unofficial NeurIPS2023 side-event
# ELLIS Machine Learning for Molecules Discovery workshop